### ISSUE TITLE
Can't find the file 'GUI.py' 

### ISSUE THREAD

**Issue by invader43** [wannabecsguy2/ISODATA_Classifier#1]
The file mentioned in the documentation named 'GUI.py' is not there in the directory of this repo , probably misplaced , add it as soon as possible.

Regards ,
invader43

**Comment by wannabecsguy2** [comment]
Adding it in a couple of days. Thank you for mentioning it @invader43.

**Comment by invader43** [comment]
> Adding it in a couple of days. Thank you for mentioning it @invader43.

Im guessing you already have the file and it takes few seconds to upload it , but take your time .


With regards ,
invader43

**Comment by invader43** [comment]
> Adding it in a couple of days. Thank you for mentioning it @invader43.

Its been a long time , I'm glad that you are taking for time to upload a single file .


Thanks and Regards
invader43
